/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 3f414670-e5c5-4d12-8d47-c849bb1e2933

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module formalizes the statement of Thue's approximation theorem and proves Siegel's Lemma, a key auxiliary result.

The main result is `ThueApproximationStatement`, which states that for any algebraic number ξ of degree d ≥ 3 and any ε > 0, there are only finitely many rational numbers p/q such that |ξ - p/q| < 1/q^(1+d/2+ε).

The module also proves `siegel_lemma_final_v2`, which guarantees the existence of a small integer solution to a system of linear equations. This lemma is crucial for constructing the auxiliary polynomial in the proof of Thue's theorem. The proof of Siegel's Lemma relies on the Pigeonhole Principle and several helper lemmas bounding the size of the relevant sets.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
The statement of Thue's approximation theorem: Given an algebraic real number ξ of degree d >= 3, for every epsilon > 0 there are only finitely many rational numbers p/q such that |ξ - p/q| < 1/q^(1+d/2+epsilon).
-/
def ThueApproximationStatement : Prop :=
  ∀ (ξ : ℝ) (hξ : IsAlgebraic ℚ ξ),
    let d := (minpoly ℚ ξ).natDegree
    3 ≤ d →
    ∀ ε > 0, Set.Finite {r : ℚ | |ξ - r| < 1 / (r.den : ℝ) ^ (1 + d / 2 + ε)}

/-
Helper inequality for Siegel's Lemma: If K is large enough and B > 0, then (2K+1)^N > (2NBK+1)^M.
-/
lemma siegel_inequality (M N B K : ℕ) (hMN : M < N) (hB : 0 < B) (hK : (2 * N * B : ℝ) ^ ((M : ℝ) / ((N : ℝ) - (M : ℝ))) ≤ K) :
    (2 * N * B * K + 1) ^ M < (2 * K + 1) ^ N := by
      -- We'll use that $K \geq (2NB)^{M/(N-M)}$ implies $K^{N-M} \geq (2NB)^M$.
      have h_exp : (K : ℝ) ^ (N - M) ≥ (2 * N * B) ^ M := by
        refine' le_trans _ ( pow_le_pow_left₀ ( by positivity ) hK _ );
        rw [ ← Real.rpow_natCast _ ( N - M ), ← Real.rpow_mul ( by positivity ), Nat.cast_sub hMN.le ] ; norm_num [ show ( N : ℝ ) - M ≠ 0 by exact sub_ne_zero_of_ne ( mod_cast hMN.ne' ) ];
      -- By multiplying both sides of the inequality $K^{N-M} \geq (2NB)^M$ by $(2K + 1)^M$, we get $(2K + 1)^M * K^{N-M} \geq (2K + 1)^M * (2NB)^M$.
      have h_mult : (2 * K + 1 : ℝ) ^ M * K ^ (N - M) ≥ (2 * K + 1 : ℝ) ^ M * (2 * N * B) ^ M := by
        gcongr;
      -- By multiplying both sides of the inequality $(2K + 1)^M * K^{N-M} \geq (2K + 1)^M * (2NB)^M$ by $(2K + 1)^{N-M}$, we get $(2K + 1)^N \geq (2K + 1)^M * (2NB)^M * (2K + 1)^{N-M}$.
      have h_mult2 : (2 * K + 1 : ℝ) ^ N ≥ (2 * K + 1 : ℝ) ^ M * (2 * N * B) ^ M := by
        refine le_trans h_mult ?_ ; rw [ show ( 2 * K + 1 : ℝ ) ^ N = ( 2 * K + 1 ) ^ M * ( 2 * K + 1 ) ^ ( N - M ) by rw [ ← pow_add, Nat.add_sub_of_le hMN.le ] ] ; gcongr ; nlinarith [ show ( K : ℝ ) ≥ 0 by positivity ] ;
      rcases M with ( _ | M ) <;> norm_cast at * ; simp_all +decide [ pow_succ, mul_assoc ];
      · exact one_lt_pow₀ ( by linarith ) ( by linarith );
      · refine' lt_of_lt_of_le _ h_mult2;
        rw [ ← mul_pow ] ; gcongr ; nlinarith [ show 0 < 2 * N * B by nlinarith ] ;

/-
The box of integer vectors of dimension n with components bounded by R has cardinality (2R+1)^n.
-/
def box (n : ℕ) (R : ℕ) : Finset (Fin n → ℤ) :=
  Finset.Icc (fun _ => -R) (fun _ => R)

lemma card_box (n R : ℕ) : (box n R).card = (2 * R + 1) ^ n := by
  erw [ Finset.card_map, Finset.card_pi ] ; norm_num ; ring;
  norm_cast

/-
The image of the box of size K under the matrix A with entries bounded by B is contained in the box of size NBK.
-/
lemma image_subset_box {M N : ℕ} (A : Matrix (Fin M) (Fin N) ℤ) (B K : ℕ)
    (hB : ∀ i j, |A i j| ≤ B) :
    Finset.image (fun x => Matrix.mulVec A x) (box N K) ⊆ box M (N * B * K) := by
      -- By definition of the image, for any $y$ in the image, there exists $x$ in the original box such that $y = A x$.
      intros y hy
      obtain ⟨x, hx, rfl⟩ := Finset.mem_image.mp hy;
      -- By definition of matrix multiplication, each component of $A.mulVec x$ is a sum of terms of the form $A i j * x j$.
      have h_comp : ∀ i, abs (A.mulVec x i) ≤ N * B * K := by
        intros i
        have h_comp : abs (A.mulVec x i) ≤ ∑ j, abs (A i j) * abs (x j) := by
          simpa only [ ← abs_mul, Matrix.mulVec, dotProduct ] using Finset.abs_sum_le_sum_abs _ _;
        -- Since $|A i j| \leq B$ and $|x j| \leq K$ for all $j$, we have $|A i j| * |x j| \leq B * K$.
        have h_bound : ∀ j, abs (A i j) * abs (x j) ≤ B * K := by
          exact fun j => mul_le_mul ( hB i j ) ( show |x j| ≤ K from by simpa using abs_le.mpr ⟨ by exact Finset.mem_Icc.mp hx |>.1 j, by exact Finset.mem_Icc.mp hx |>.2 j ⟩ ) ( by positivity ) ( by positivity );
        exact h_comp.trans ( le_trans ( Finset.sum_le_sum fun _ _ => h_bound _ ) ( by norm_num; linarith ) );
      exact Finset.mem_Icc.mpr ⟨ fun i => neg_le_of_abs_le <| mod_cast h_comp i, fun i => le_of_abs_le <| mod_cast h_comp i ⟩

lemma siegel_lemma_collision {M N : ℕ} (A : Matrix (Fin M) (Fin N) ℤ) (B K : ℕ)
    (hB : ∀ i j, |A i j| ≤ B)
    (h_card : (2 * N * B * K + 1) ^ M < (2 * K + 1) ^ N) :
    ∃ (x : Fin N → ℤ), (∃ i, x i ≠ 0) ∧ (∀ i, |(x i : ℝ)| ≤ 2 * K) ∧ Matrix.mulVec A x = 0 := by
      -- By the pigeonhole principle, since $|S| > |T|$, there exist distinct vectors $x_1$ and $x_2$ in $S$ such that $ Ax_1 = Ax_2$.
      obtain ⟨x1, x2, hxy⟩ : ∃ x1 x2 : Fin N → ℤ, x1 ≠ x2 ∧ x1 ∈ box N K ∧ x2 ∈ box N K ∧ A.mulVec x1 = A.mulVec x2 := by
        by_contra! h_contra;
        have h_pigeonhole : Finset.card (Finset.image (fun x : Fin N → ℤ => Matrix.mulVec A x) (box N K)) ≤ Finset.card (box M (N * B * K)) := by
          exact Finset.card_le_card ( image_subset_box A B K hB );
        rw [ Finset.card_image_of_injOn fun x hx y hy hxy => by contrapose! hxy; exact h_contra x y hxy hx hy ] at h_pigeonhole ; simp_all +decide [ card_box ];
        exact h_card.not_le ( by simpa only [ mul_assoc ] using h_pigeonhole );
      use x1 - x2;
      simp_all +decide [ funext_iff, Matrix.mulVec ];
      exact ⟨ by simpa [ sub_eq_zero ] using hxy.1, fun i => abs_le.mpr ⟨ by linarith [ show ( x1 i : ℝ ) ≥ -K by exact_mod_cast Finset.mem_Icc.mp hxy.2.1 |>.1 i, show ( x2 i : ℝ ) ≤ K by exact_mod_cast Finset.mem_Icc.mp hxy.2.2.1 |>.2 i ], by linarith [ show ( x1 i : ℝ ) ≤ K by exact_mod_cast Finset.mem_Icc.mp hxy.2.1 |>.2 i, show ( x2 i : ℝ ) ≥ -K by exact_mod_cast Finset.mem_Icc.mp hxy.2.2.1 |>.1 i ] ⟩ ⟩

theorem siegel_lemma {M N : ℕ} (A : Matrix (Fin M) (Fin N) ℤ) (hMN : M < N) (B : ℕ)
    (hB : ∀ i j, |A i j| ≤ B) (hB_pos : 0 < B) :
    ∃ (x : Fin N → ℤ), (∃ i, x i ≠ 0) ∧ (∀ i, |(x i : ℝ)| ≤ 2 * (2 * N * B : ℝ) ^ (M / (N - M : ℝ))) ∧ Matrix.mulVec A x = 0 := by
      -- Let $K = \lfloor (2NB)^{M/(N-M)} \rfloor$.
      set K := Nat.floor ((2 * N * B : ℝ) ^ ((M : ℝ) / ((N : ℝ) - (M : ℝ)))) with hK;
      by_cases h : ( 2 * N * B * K + 1 : ℝ ) ^ M < ( 2 * K + 1 ) ^ N <;> simp_all +decide [ Nat.floor_le ];
      · -- By `siegel_lemma_collision`, there exists $x$ such that $Ax=0$, $x \ne 0$, $|x_i| \le 2K$.
        obtain ⟨x, hx_nonzero, hx_abs, hx_eq⟩ : ∃ (x : Fin N → ℤ), (∃ i, x i ≠ 0) ∧ (∀ i, |(x i : ℝ)| ≤ 2 * K) ∧ A.mulVec x = 0 := by
          convert siegel_lemma_collision A B K hB _ using 1 ; norm_cast at * ; aesop;
        exact ⟨ x, hx_nonzero, fun i => le_trans ( hx_abs i ) ( mul_le_mul_of_nonneg_left ( Nat.floor_le ( by positivity ) ) zero_le_two ), hx_eq ⟩;
      · contrapose! h;
        -- By simplifying, we can see that this inequality holds for sufficiently large $K$.
        have h_simp : (2 * N * B : ℝ) ^ M < (2 * K + 1) ^ (N - M) := by
          have h_simp : (2 * N * B : ℝ) ^ (M / (N - M) : ℝ) < 2 * K + 1 := by
            linarith [ Nat.lt_floor_add_one ( ( 2 * N * B : ℝ ) ^ ( M / ( N - M ) : ℝ ) ) ];
          exact lt_of_le_of_lt ( by rw [ ← Real.rpow_natCast _ ( N - M ), ← Real.rpow_mul ( by positivity ), Nat.cast_sub hMN.le, div_mul_cancel₀ _ ( sub_ne_zero_of_ne ( by norm_cast; linarith ) ) ] ; norm_num ) ( pow_lt_pow_left₀ h_simp ( by positivity ) ( Nat.sub_ne_zero_of_lt hMN ) );
        rw [ show ( 2 * N * B * K + 1 : ℝ ) ^ M = ( 2 * N * B ) ^ M * ( K : ℝ ) ^ M * ( 1 + 1 / ( 2 * N * B * K ) ) ^ M by
              rw [ ← mul_pow, ← mul_pow ];
              by_cases h : ( 2 * N * B * K : ℝ ) = 0 <;> simp_all +decide [ mul_add, add_mul, mul_assoc, mul_comm, mul_left_comm ];
              rcases h with ( rfl | rfl | h ) <;> norm_num at *;
              exact False.elim <| h.not_le <| Real.one_le_rpow ( by norm_cast; nlinarith [ show N > 0 from pos_of_gt hMN ] ) <| div_nonneg ( Nat.cast_nonneg _ ) <| sub_nonneg_of_le <| Nat.cast_le.mpr hMN.le ];
        refine' lt_of_lt_of_le ( mul_lt_mul_of_pos_right ( mul_lt_mul_of_pos_right h_simp ( pow_pos ( Nat.cast_pos.mpr <| Nat.floor_pos.mpr <| Real.one_le_rpow ( by norm_cast; nlinarith [ show ( N : ℝ ) * B > 0 by norm_cast; nlinarith ] ) <| by exact div_nonneg ( Nat.cast_nonneg _ ) <| sub_nonneg.mpr <| Nat.cast_le.mpr hMN.le ) _ ) ) <| pow_pos ( add_pos_of_pos_of_nonneg zero_lt_one <| one_div_nonneg.mpr <| by positivity ) _ ) _;
        rw [ show ( 2 * K + 1 : ℝ ) ^ N = ( 2 * K + 1 ) ^ ( N - M ) * ( 2 * K + 1 ) ^ M by rw [ ← pow_add, Nat.sub_add_cancel hMN.le ] ];
        rw [ mul_assoc ];
        rw [ ← mul_pow ];
        gcongr;
        rcases eq_or_ne K 0 <;> simp_all +decide [ division_def ];
        · norm_num [ ← hK ] at *;
        · field_simp;
          rw [ mul_add, mul_div ];
          rw [ add_div', div_le_iff₀ ] <;> ring <;> norm_cast <;> norm_num;
          · nlinarith [ show 0 < N * B by exact mul_pos ( Nat.cast_pos.mpr ( pos_of_gt hMN ) ) hB_pos, show ⌊ ( ( N : ℝ ) * B * 2 ) ^ ( ( M : ℝ ) * ( N - M : ℝ ) ⁻¹ ) ⌋₊ ≤ N * B * ⌊ ( ( N : ℝ ) * B * 2 ) ^ ( ( M : ℝ ) * ( N - M : ℝ ) ⁻¹ ) ⌋₊ by exact le_mul_of_one_le_left ( Nat.zero_le _ ) ( by nlinarith [ show 0 < N * B by exact mul_pos ( Nat.cast_pos.mpr ( pos_of_gt hMN ) ) hB_pos ] ) ];
          · exact ⟨ pos_of_gt hMN, Nat.floor_pos.mpr <| by ring_nf at *; linarith ⟩;
          · grind

theorem siegel_lemma_final {M N : ℕ} (A : Matrix (Fin M) (Fin N) ℤ) (hMN : M < N) (B : ℕ)
    (hB : ∀ i j, |A i j| ≤ B) (hB_pos : 0 < B) :
    ∃ (x : Fin N → ℤ), (∃ i, x i ≠ 0) ∧ (∀ i, |(x i : ℝ)| ≤ 4 * (2 * N * B : ℝ) ^ (M / (N - M : ℝ))) ∧ Matrix.mulVec A x = 0 := by
      revert hMN hB hB_pos;
      intro hMN hB hB_pos
      obtain ⟨x, hx_nonzero, hx_bound, hx_zero⟩ : ∃ x : Fin N → ℤ, (∃ i, x i ≠ 0) ∧ (∀ i, |(x i : ℝ)| ≤ 2 * (2 * N * B : ℝ) ^ (M / (N - M : ℝ))) ∧ Matrix.mulVec A x = 0 := by
        apply_rules [ siegel_lemma ];
      exact ⟨ x, hx_nonzero, fun i => le_trans ( hx_bound i ) ( mul_le_mul_of_nonneg_right ( by norm_num ) ( by positivity ) ), hx_zero ⟩

theorem siegel_lemma_final_v2 {M N : ℕ} (A : Matrix (Fin M) (Fin N) ℤ) (hMN : M < N) (B : ℕ)
    (hB : ∀ i j, |A i j| ≤ B) (hB_pos : 0 < B) :
    ∃ (x : Fin N → ℤ), (∃ i, x i ≠ 0) ∧ (∀ i, |(x i : ℝ)| ≤ 4 * (2 * N * B : ℝ) ^ (M / (N - M : ℝ))) ∧ Matrix.mulVec A x = 0 := by
      convert siegel_lemma_final A hMN B hB hB_pos using 1